document:
  name: Document implementing the INGV data policy
  description: |
    Document implementing the data policy of the Istituto Nazionale di Geofisica e Vulcanologia.
  tags:
    - INGV
    - data policy
    - database
    - dataset
    - scientific research
    - metadata
    - FAIR
